# Generated by Django 5.0.9 on 2024-11-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('instid', models.AutoField(db_comment='Auto incremental', primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(db_comment='E.x. IMF', max_length=24, unique=True)),
                ('name', models.CharField(db_comment='E.x. International Monetary Fund.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=24, null=True)),
                ('country', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'institution',
                'managed': False,
            },
        ),
    ]
