CREATE TABLE "institution" (
  "instid" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "abbreviation" varchar(24) UNIQUE NOT NULL,
  "name" varchar(255) UNIQUE NOT NULL,
  "description" text,
  "url" varchar(255),
  "type" varchar(24),
  "country" varchar(36),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "indicator" (
  "inst_instid" integer,
  "indicid" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "group" text,
  "description" text,
  "unit" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "unified_indicator" (
  "uindicid" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "description" text,
  "unit" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "area" (
  "areaid" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "code" varchar(255) UNIQUE NOT NULL,
  "name" varchar(255) UNIQUE NOT NULL,
  "description" text,
  "currency" varchar(255),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "publishes" (
  "pub_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "inst_instid" integer,
  "indic_indicid" integer,
  "area_areaid" integer,
  "date_published" timestamp NOT NULL,
  "date_from" timestamp NOT NULL,
  "date_until" timestamp NOT NULL,
  "value" integer NOT NULL,
  "is_forecast" char(1) NOT NULL
);

CREATE TABLE "mapping" (
  "map_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "indic_indicid" integer,
  "uindic_indicid" integer,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "formula" text
);

COMMENT ON COLUMN "institution"."instid" IS 'Auto incremental';

COMMENT ON COLUMN "institution"."abbreviation" IS 'E.x. IMF';

COMMENT ON COLUMN "institution"."name" IS 'E.x. International Monetary Fund.';

COMMENT ON COLUMN "indicator"."indicid" IS 'Auto incremental';

COMMENT ON COLUMN "indicator"."name" IS 'E.x. GDP';

COMMENT ON COLUMN "unified_indicator"."uindicid" IS 'Auto incremental';

COMMENT ON COLUMN "unified_indicator"."name" IS 'E.x. GDP';

COMMENT ON COLUMN "area"."areaid" IS 'Auto incremental';

COMMENT ON COLUMN "publishes"."pub_id" IS 'Auto incremental';

COMMENT ON COLUMN "mapping"."map_id" IS 'Auto incremental';

ALTER TABLE "indicator" ADD FOREIGN KEY ("inst_instid") REFERENCES "institution" ("instid");

ALTER TABLE "publishes" ADD FOREIGN KEY ("inst_instid") REFERENCES "institution" ("instid");

ALTER TABLE "publishes" ADD FOREIGN KEY ("indic_indicid") REFERENCES "indicator" ("indicid");

ALTER TABLE "mapping" ADD FOREIGN KEY ("indic_indicid") REFERENCES "indicator" ("indicid");

ALTER TABLE "mapping" ADD FOREIGN KEY ("uindic_indicid") REFERENCES "unified_indicator" ("uindicid");

ALTER TABLE "publishes" ADD FOREIGN KEY ("area_areaid") REFERENCES "area" ("areaid");
