# Generated by Django 5.0.9 on 2024-11-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('indicid', models.AutoField(db_comment='Auto incremental', primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='E.x. GDP', max_length=255, unique=True)),
                ('group', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'indicator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('map_id', models.AutoField(db_comment='Auto incremental', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publishes',
            fields=[
                ('pub_id', models.AutoField(db_comment='Auto incremental', primary_key=True, serialize=False)),
                ('date_published', models.DateTimeField()),
                ('date_from', models.DateTimeField()),
                ('date_until', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('is_forecast', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'publishes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnifiedIndicator',
            fields=[
                ('uindicid', models.AutoField(db_comment='Auto incremental', primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='E.x. GDP', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unified_indicator',
                'managed': False,
            },
        ),
    ]
